package com.zoho.utilities;

import java.io.File;
import java.io.FileOutputStream;
import java.util.Date;

import org.springframework.stereotype.Component;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.zoho.entity.Billing;
@Component
public class PdfGenerator {
	 
    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);
    
    
   // public  void generatePDF(String filePath,  String firstName,String lastName, String email, String mobile,String product,int amount) {
     public void  generatePDF(Billing bill ,String filepath) {
    try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(filepath));
            document.open();
            document.add(generateTable(bill,document));
            //addMetaData(document);
           // addTitleAndTable(document, firstName,lastName,  email,  mobile, product, amount);
            document.close();
        } 
        catch (Exception e) 
        {
           System.out.println(e); 
        }
    }
        private PdfPTable generateTable(Billing bill,Document document) throws DocumentException {
	// TODO Auto-generated method stub4
        	Paragraph preface = new Paragraph();
            
            
            preface.add(new Paragraph("Billing   Details", catFont));

           
            preface.add(new Paragraph(
                    "Report generated by: " + " bill generated markerting Company " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                    smallBold));
            document.add(preface);  
            document.add( Chunk.NEWLINE );
            document.add( Chunk.NEWLINE );
        	PdfPTable table=new PdfPTable(2);
        	PdfPCell cell;
//        	cell=new PdfPCell(new Phrase("billing page"));
//        	cell.setColspan(2);
        	//table.addCell(cell);
        	cell=new PdfPCell(new Phrase("billing page details"));
        	
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setColspan(2);
        	table.addCell(cell);
        	long id = bill.getId();
        	
        	
        	String a=String.valueOf(id);
        	table.addCell("bill id");
        	table.addCell(a);
        	table.addCell("firstname");
        	table.addCell(bill.getFirstName());
        	table.addCell("lastname");
        	table.addCell(bill.getLastName());
        	table.addCell("email");
        	table.addCell(bill.getEmail());
        	table.addCell("mobile");
        	table.addCell(bill.getMobile());
          	table.addCell("product");
        	table.addCell(bill.getProduct());
        	table.addCell("amount");
        table.addCell(bill.getAmount());
		return table;
	
}
		

}
